### ISSUE TITLE
Dynamic size of the overlay

### ISSUE THREAD

**Issue by Raphael-Bahuau** [tisdadd/configured-dnd-context#2] opened 2024-01-02 10:03 UTC
I have a sortable item with a `renderOverlayItem` function in it.

I wan't to set the width & height dynamicaly according to the container configuration (I have one container wich the item size are bigger than the others).

I have the sizes per container cached in a store (cause an nother container in the app depend on them).

I juste wan't to get the id from the over container, I tought I can use `active` from `useConfiguredDnd` but when I log it, sometimes it's `null`.

I'm sure you have a conventionnal way to do this, can you help me ?

```js

export function SortableItem({ item, children }) {

  const { active, getItem } = useConfiguredDnd();

  const store = useStore();

  function renderOverlayItem() {
    const item = getItem(item.id);
    console.log(active); // sometime equal null I don't know why ?
    const overContainerId = active?...
    const { width, height } = store.sizes[overContainerId];
    return (
      <Box cursor="grabbing" w={width} h={height}>
        {children}
      </Box>
    );
  }
  
  // Rest of the component...
}
```

**Comment by tisdadd** [comment] 2024-01-02 19:51
Reading and looking through this, I am assuming that what you really want is the `over.data.current?.sortable?.containerId || over.id`. As I was typing up what is below, I realized that the feature was there, just not exposed - so 1.0.9 is just exposing an renaming it. You should just need to do `const { active, getItem, overContainerId } = useConfiguredDnd();` to get it now.

However, since I had it mostly typed up, here is the original in case you want the actual over component, not just the id.

This base doesn't currently track full over component, just current active. If you are wanting to morph what it looks like when it is over a specific container in the overlay then I would do the following pattern - very similar to the base kit, but through hooks on your specific item. 

```js
export function SortableItem({ item, children }) {
... start
  const [over, setOver] = useState(null);

 const {setNodeRef, ...rest} = useSortable({
   id: item.id,
   data: {
    // ...rest
     /** What to do when this item moves over another - it is a hook into the DndContext onDragOver with this item
     * being the active one
     */
      onDragOver: ({over})=>{
             setOver(over)
      }
    }
})

  function renderOverlayItem() {
    const item = getItem(item.id);
    console.log(active); // sometime equal null I don't know why ?
    const overContainerId = over.data.current?.sortable?.containerId || over.id
    const { width, height } = store.sizes[overContainerId];
    return (
      <Box cursor="grabbing" w={width} h={height}>
        {children}
      </Box>
    );
  }
  
  // Rest of the component...
 // return something with the {setNodeRef} above and the data
}
```

Note that I personally wouldn't keep in a separate cache somewhere, but instead on registering the items.
```js
// in useEffect
registerItemGroup(
{...rest,
  data: {width, height}
}
```

And access via `getItemGroupData` later.

Anyway, please let me know if there are any further questions or if it doesn't work?

**Comment by Raphael-Bahuau** [comment] 2024-01-03 09:03
I've tried the `onDragOver` solution to set an over variable but this doesn't work properly.

The event don't seem to trigger properly...

I don't think this is related directly to your library, maybe we can make a visio so I can show you i a better way ?

**Comment by tisdadd** [comment] 2024-01-03 17:00
@Raphael-Bahuau thanks for the update. I just played with things and realized that, since the element is in a portal, the value should be passed there as well to be useful as otherwise you are out of the context leading to some unexpected behaviors. As such, I have created a [story specific to this](https://tisdadd.github.io/configured-dnd-context/?path=/story/storycomponents-githubextraexamples-github2dynamicsizeoftheoverlay--default), with containers that warp squares to three separate sizes - please [check out the code](https://github.com/tisdadd/configured-dnd-context/blob/main/StoryComponents/GithubExtraExamples/Github2DynamicSizeOfTheOverlay.stories.tsx).

If you want to make a visio to share, please feel free to do so. Sorry about the confusion - this does seem like a good use case to me.

**Comment by Raphael-Bahuau** [comment] 2024-01-04 13:21
I've managed to morph the dragged item, but now I struggle with the copy function, I wan't to copy item from juste a virtual grid (not in Sortable contexte cause they can't moove, only copy to other sortable container).

I use the `registerNonGroupedItem` function, but when I drop the item in a sortable container, it's somewhat linked to the original one.

I've tried both with and without `maintainOriginalIds`.

The thing I really want it when I copy an item, the one I drag is not the original, but a new item dynamically created on dragStart.

**Comment by tisdadd** [comment] 2024-01-04 17:34
So, the way that the underlying library works - from what I know - you will not be able to make the new item on drag start. It associates everything by id (hence if you have `maintainOriginalIds = true` here it will show going back to the original position). I believe any of the stories labeled `Sortable Container With Add And Remove Drag and Drops` should show this working, such as [this one](https://tisdadd.github.io/configured-dnd-context/?path=/story/useconfigureddnd--sortable-container-with-add-and-remove-drag-and-drops). When you say somewhat linked to the original I might need to see your code more.

Below is the copiable drag square from those stories. 

```tsx
<DragSquare
                sortable={true}
                dndCopy={true}
                dndMaintainOriginalId={true}
                extraText={`${value.getItem('DragCopy')?.item || 1}`}
                value={value}
                id='DragCopy'
                selfContained={true}
                itemDataFunction={() => ({
                  onDragEnd: () => {
                    value.updateItem(
                      'DragCopy',
                      Number(value.getItem('DragCopy')?.item || 1) + 1
                    )
                  }
                })}
              />
```

From a final draggable element that translates to your standalone item being registered just as you are doing, using the `useSortable` hook _instead of_ `useDraggable` as otherwise there was weird behavior. Depending upon what you are wanting to do, you should be able to use `onDragEnd` to set new item data based upon the active it receives if the linking had to do with data?

Do you have an example somewhere that can be shared if you would like more assistance?

**Comment by Raphael-Bahuau** [comment] 2024-01-04 18:14
The concept I imagine to clone an element on dragStart is :
- check if the element is a clonable one
- cancel the drag event on it
- create a new element with same the same component logic but with a new id
- somewhat re attach the drag start event on the new element

With this technique, the original dragged element is in fact never re-render !

Anyway I think I can't make it work cause I never code the dragEnd event to actualise the item list state wich from the sortable item are registered.

**Comment by tisdadd** [comment] 2024-01-04 19:44
Do you have a working example up to that point somewhere that I could see? Otherwise, feel free to fork this and play, and if you are able to get it to work make a pull request.

I think this is outside the direct scope of this project, and since the example with changing number per list I was able to run on some older hardware (2011 Macbook) with over 900 drag elements (extra 300 each) with very minor lag (1500 was more noticable) I am not sure it is well worth it - though it does sound pretty cool if you are able to pull it off. 

Anyway, if you do have an example I can take a look at maybe being able to do the same here.

It seems like the approach you are proposing would need a custom [sensor](https://docs.dndkit.com/api-documentation/sensors) setup?

**Comment by tisdadd** [comment] 2024-01-15 20:36
Closing as we made it through the main question and no more discussion has happened for a few weeks.

**Closed as completed by tisdadd** 2024-01-15 20:36 UTC

**Comment by Raphael-Bahuau** [comment] 2024-01-15 22:57
Sorry, I don't have any exemple anymore.
I figured out I was needed more control on the original lib to use it with Framer Motion, I ended up dive deep into the source to write custom collision algorith, render method without drag overlay etc...
